export const SocketEvents = {
  JOIN_ROOM: 'JOIN_ROOM',
  CREATE_ROOM: 'CREATE_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  MOVE_PIECE: 'MOVE_PIECE',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  USER_CONNECTED: 'USER_CONNECTED',
  CHECKMATE: 'CHECKMATE',
};
